apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sda133213s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sda133213s 
  name: sda133213s
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sda133213s 
