apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sda133213s
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/sda133213s/overlays/development
    repoURL: https://github.com/stephanie-cy/sda133213s-gitops
    targetRevision: main
  destination:
    namespace: sda133213s
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: openshift-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
